services:
  - type: web
    name: con-dfr-website
    env: node
    buildCommand: npm install
    startCommand: node server-v2.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1